---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: roundy-app
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCrdlbBgkG9y6COrEPSdgvNP8QEbhXCNwnDPQQuw8x9fvYrxioM9SkO/mqiQA8iklCKupMhPt2t0X7HaN7Br8bW9s+Hkq6zsWg0rYQEyMHnEgadNe+XAKwwEHMx1EAdkQOXc+FjhiEreR14/Rr/BcWlfPkMDS/fhXMwshEsGrPYglMtXpw8RF2qIRqYj1ql7MvYQQ/0g054kTOqxReJTpGtDx6blpEEGDbwnmLGknMWzJiRSfwvqtjMsa+tQ4HsYDeem76Z8l29HXbbquanFSE0VU0qyyog++DvUEW2E8MiU4O3WTSrGeUjSSgX0BypEDV/oPXWN8N+3XponmJNPYwjhWmKqM2u2lG+trHjgSSNSSGifnxUkspWPXGGZk9WfL9ol9LW92w2kTVd/92+7uhm+ciqgDSAzxdhnlw9Luq08WtQJzj4RV88K0IalKptpjVcFMBi5gXubJaOhssa9d90L7lXhWcs9Qk9Hu4+MN/hdQy9LRqlS0kUpdX+DiwVkqlaNoomI2gS4LQAiyW1wAZ0tWCoxHqjSy/ilaID+ShZFd/MoAKzqiyqGahCWCJogmiwRXm7XpgwixyD+CD+gGSO4JJ8dllbBgaFHVNs66nYqLt5oY1FtDlBkRwQwI/AZOblU4gnv8x6ljY+NdKtVa4FiHzEPzpgvRYXapULoCM6a/OsPkuL3vMoUmzN1t/ZnwtJ5oeNTSm53BqOuaAAPg==
    MINIO_ROOT_USER: AgCzURb/WSK1/bQTU134VhW61TDo2WW2c9XN11LR+B1Z0/t+G9wKzuj7XLsT88HacrrCxPqsGTMXyA3XOdMMp8sRrLAGZ4vA7USYuy1qbg+4U45RkGTcOzdhXBuikkUaxw+29NJLc+vV+X5OdIHqXn6tDXP/tjnZ5Fm9ovu5Wo4NcF642csl/OteRoX1hYOABJ2iLIT5kmX30letbINq/lAdUL+vTAhr06Kb7i4B2EqUcgvm1MYThnT1DA0fiWq6OBkTvn4+0fbyFURO6UIcUzbwYPaTVn4vWCfrk7W5zUTvoIv+6kdADlX+5WuSio35igMJwF4SIG1NccohbYis5uiff4xLKOceISh2Mz5f7OIiNNIZsupdN0e1bR2YaLxyFLoRR44LwVPtNWOaP7+qCPI3rV0wAD0DkRLsyi/7XeN/7JEiKZJ+18Q5np0qVrWRu5UEio/21KNwh7pn1L3omlr8a0dRYRfil/mgWZLv+Yqt5rFbZHVDezpPQaRSuHOKgjchm1FtLO5kG4t/3q3hmjzOzOqpEDJPYD1TZJ5XUSLk86/aja0Of7iO9T8SMtEW8rsm+nRPWfaScCy4dc0RJiFui3Ug/M8EeNmij5dVCwYPLTIaB575TN46oslp3t1vwLZ1fRZM04+mUMwpAd3M9EMzZBnnzC0F5q1XSoMQkMYQuM1LVJMhOOMVODsql/LnID2iYJKsoA==
  template:
    metadata:
      name: minio-secret
      namespace: roundy-app
    type: Opaque
