---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: roundy-app
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgCJ+kaHkm531aMGYTeZeHr/9SsRKtAsIEilcxH8d88VEXAflIPK2gq2yhA+Z+I+nk05xaIiXq8jAORehlD/hcD6gkyBWUZrLZcyTIAhU8GWybe+w2MehmWDZxc6V314n5/4uRKf9D7un8yYCVyzPuXK/y72KpFW9JarNo0xPxS8ghSoPUH1N6gacAq64Ttv7JzdeJzW2aMF68eLoa4ihdS5uwe2y7+mECXLYTKgIMxcs8wDFGVAXx7ZJlzKqP7ksNMGxEoMDyGUwo1xuosWZaRwmpqJB44VsRNYOjuHWouqL2R4i4Q9gpjyh5rH4sgNJ/296ZYQDOkAyW8GdAFzARmR3Dn02hlX54RQHs7ehXjyxTZeiWITPunZ/4D3vuxXgPDbGKuHBYmR2+RFWoT2L4kVhvlIWWJFWWMNQT3SrmnVm56qU0CQH7OsnU4l7PS8ez/yBoKAm4eCLK4hMM25MtZMjQvkHmPFbxaFLzAfwveK7kZ8CkwQHMkHtiBAa7Jk7eRqJvveXSDMNgpWIg+Kbz8sh3X2rY62OwI3HqyOD5Gx4qd8l8bzXfPA1dSsCm6EOEHQAOHUw98HIZguNKiRw5dq/JOEN3bEo3y3+YGLtFgfmaZ78qyEWZExgTASwE4skj0Uz3O5r0qWgmKv6CrJ5kNEx/SmJb2fSeUQkgQsUh2Nw+TRqQTD7FSVCghy9LFE9u0Mux6s
    MINIO_SECRET_KEY: AgApbDsbW+k56NZBFHkWfxAHYvKMC+Jtq/wEDyipMRzi1bRAvw1lwsG6xiu/4GHMxlc5Dad1t9Fr8kDW0Qkg17l1+W6zAmOySwimXO0B2UXeUjY0cuSCov4HiBH76GYw8bGI1JeuQJapmbh87wh6YtNM5+OUl7i5disB8ie0/sXyym0iQ/Rl+n+jpypeh8h5hYsUqLRdukoKPnnWIdJc68PN+r/2gTIlMnPcImiI827RoWioLEziRu+HEMshA66VOd73PglNlh/RDz5B0YexLANMdeSn/yzE1M1mppxhPCeXuhNjH2sqBLscnZXENjlsi+I80YGvTUxN7ReNq7/abNKfk2jqnKBXItGMV/ZecsbZFLvk6W9tf/DX0p+NtNxqpwjdwPyVplATClsy0UX+2YRLiR4sMaDzsB2882YVKz9uUTJ1cScpR4v+c2g/D3CPrnMOnygsV3+jiEMxi73yIgqgEvL1lqIGbnroDNixVMg95OgrFSqEF1naRdyW8lM37WrSO8kyoImu/zFP8V5luZ1cypfV1iKYvE4wgEhrLTY4ggGI4DUsVuAleBahmUSdhhpe1DvsZLP2eA4H7OttRKrG0H1g3uSEVE4sz2q5ysj7ZSxq7/uwggbbv/rM+YfQx+wkWQFCxQC78ezsu2bSaXfYznHDcRTfKCETmtt/msJdWZpXUXEEbR3uueXGSGc1Rg6x1gmndKiibY9o2JaF0A==
  template:
    metadata:
      name: minio-secret
      namespace: roundy-app
    type: Opaque
