---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-secret
  namespace: roundy-app
spec:
  encryptedData:
    password: AgDXUEPzhkr+xNBqppjmQJh6j17zmXElogdjSRDnFXQimo4GkAX/3YnDGGJDmHJWEp1AKdibjsnJxoyrmtkNweV3i3gjPToGSirAzbDoAOTGpKJTNX4rqbpAzga5ewgM0UUg54G7A0kj6xbCmAoBlTvk+x2ykyz8K45k6e9BD0DVNYboXbbqTSqjwdZaoOcXFRyqVSaXyj5byVFhzElk92PXOoDCsxnSbj3wNuPTU52/E5wHkwoMGFfk4i/eNNbZS91izEciRXZggYY5yTA648Hi/P8Qi46qrFxCZ+yvCBxJSeSGj82Z5Qb5EtPP7Jhw639mlGEYMfwKneQVvfftcG/L3dap6zun8IF8ktATzoeUvXKp3se+SHB/QdYPeRIKkz4jS9q4i9GRZ/MNkse1Mst+8GcPTCS8Oa+iwE1DxDe2uCHA+FzkKKJLumjX9P6lTiStaXkYEVYN3xOrONNb6mo9y+obVeT0uJxNc9FP6sJqy3A6qshw38b5YMLj059Qxa3ZM0RURturtuw4i2cmg28E9T5yMO7jmu4r1xL2SjdL7Wb0Wrd9b9K01vaR/d/o3lFNa78Sb3qaWptcuEbI1Y/k7c5E+4LUd3YSUaCmg0cqnmx2+2Ud7taR7clrv7VhUbNwbVG0ZlzLt44t1aJvvTrQQmSpizh6ekBekqFdyd7yryM2hb9TnUtfKzwzG7+Drv6qFA+SGGCFnWscA1DfXg==
  template:
    metadata:
      name: mysql-secret
      namespace: roundy-app
    type: Opaque
