---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-secret
  namespace: default
spec:
  encryptedData:
    password: AgCBYRXdn6XFNMQIKAqyaW7XEPdb45Xzx1IVRR6morSVKuLvzBOE7x5A4BNKRTDHu74RsSt2vcwdoQMTKZAt6EJ8h+iASy+O6FBas8/LOfD+L7VzLFwSxULFvJRf7wldN4YUl4zMTrbxkri4G6X3yweFGfl37m0xR8CCwqHh8bOzUrK3nASOGlRP0Rhtt22R4G1tzCA7F5Onb6MraaFEuuI+wyXdC6J7mr7wH35qK/nANflBtJ1NHf8Iv0EmREaQ1uxQuaGsOlr2dy/3bXHMUBz9o1ho46NgCcqLa2TEZx1TNyrq3UuPwAHp655TyoeWIXNT1+IouVXE7o694rIXEUr5cX3q9oswcY1JoodZ2ScMZHSdF4cAYqQ9it1ptlaCi4prsIQqf/w5smfaV148m8D+U9YUDUkAzpiyhGCQsl0VniUnov62zmPEkaoEUkFEzMN4tgXhnMkvJXtDxgQgIXE4+B4ntp8zqKqqpO+lmaDKj0gITY1t7kSduC1f/aPvHN9SdfMRDAOFze48DnCirnJDFkt0qgEkzl3mdEwQoVS3MkrR5ey+UQGcr9YHJXYxDbXHL342nY3pmwYnmQF+Rm6edY+nts0RluthRncrRgGvK74jN5rLNNhboLEY/nt0TpLfx3JLWne9NMFhwhXgOA3Co9Gseta9yAvXCk6zvliYil1I7FX/EgNvTxffYxGuaChV+JaS9lHTagZUlJ1FKA==
  template:
    metadata:
      name: mysql-secret
      namespace: default
    type: Opaque
