---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-secret
  namespace: roundy-app
spec:
  encryptedData:
    password: AgB5QeXK7cnJC0Jt5m4rDGHvIST4r1XJQ/cmVGJ9t4WI7ARBQ6dV+a3I4DjU3YnvJVwdyHMhtebhqXjLsV1lL6PM8XX3kmRUwwTDOj8Rs9wYqXGs049mnQjrn7A4T2hJ2oFCNEpbY4DyLECliLth4CQ3qIhVnKoiFiwdSKyRZ0oFI8xW7qSfA3yNSM7z4i3Lbb3AHo6zb9+V2bfgdQhsoxev4QjDKKoxKvU3GarTp+RHlPNdiDKyLutU8fAJtXS9gKp2vUJn7a8zdo/8SAXespOyYkusX7DIg2a10fLp0VfjUiE9wQ0Qj3cea3+uO21DmllfS1nwheneDppuot/W9ZYHHrv9uVNNdHQCX/rVUt50la0fcUSLl2qdqtP+tpcg6gcNWJRoP2DXYKEjObDVeis8E0wPkSX3q5u6UVkTKVKFIlvGM0qgfmQQQv9wTU5HI76DB1k/CzA3BLzZlnla/hqHgsNdzwtR9JERpYpLxl2AoA5SrlrY6BFclW4UtBfRCGoxcpSrdLxNfDPNmItTtLBvWp0ZsSbPvtj/JR2H7spVDQaIT6TWQAldT0SCnr+AG3Rau1OD2liZ2xRSmoRorLpV7rzc+7kMNS6KRn/fR7c5hVC3OG/ni3xF+JOjuQ1ysyys4E2ksX7KpTZkzwWyN6lyaFUSB6JIRH0+ogQDmqvw0qD9rgNQyPwQRNWYqr5tTRXTz7l16sLf7rpfcPZebQ==
  template:
    metadata:
      name: mysql-secret
      namespace: roundy-app
    type: Opaque
