apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvidu-server
  namespace: roundy-app
  labels:
    app: openvidu
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: openvidu
  template:
    metadata:
      labels:
        app: openvidu
    spec:
      hostNetwork: true
      containers:
      - name: openvidu-container
        image: openvidu/openvidu-dev:2.31.0
        ports:
        - containerPort: 8443
          name: https
        - containerPort: 3478
          protocol: UDP
          name: stun-udp
        - containerPort: 5443
          protocol: TCP
          name: turn-tcp
        envFrom:
        - secretRef:
            name: openvidu-secret
        env:
        - name: OPENVIDU_PORT
          value: "8443"
        - name: SERVER_PORT
          value: "8443"
        - name: HTTPS_PORT
          value: "8443"
        - name: HTTP_PORT
          value: "80"
        - name: MIN_PORT
          value: "16384"
        - name: MAX_PORT
          value: "32768"
        - name: DOMAIN_OR_PUBLIC_IP
          value: "i14a701.p.ssafy.io"
        - name: OPENVIDU_PUBLICURL
          value: "https://i14a701.p.ssafy.io:443/openvidu/"
        - name: CERTIFICATE_TYPE
          value: "selfsigned"
        - name: TURN_PORT_TCP
          value: "5443"
        - name: TURN_PORT_UDP
          value: "3478"
---
apiVersion: v1
kind: Service
metadata:
  name: openvidu-service
  namespace: roundy-app
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: http
spec:
  selector:
    app: openvidu
  ports:
    - name: https # http로 동작
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: stun-udp
      protocol: UDP
      port: 3478
      targetPort: 3478
    - name: turn-tcp
      protocol: TCP
      port: 5443
      targetPort: 5443
  type: ClusterIP


