apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvidu-server
  namespace: roundy-app
  labels:
    app: openvidu
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: openvidu
  template:
    metadata:
      labels:
        app: openvidu
    spec:
      hostNetwork: true
      containers:
      - name: openvidu-container
        image: openvidu/openvidu-dev:latest
        ports:
        - containerPort: 4443
        envFrom:
        - secretRef:
            name: openvidu-secret
        env:
        - name: OPENVIDU_PORT
          value: "8443"
        - name: SERVER_PORT
          value: "8443"
        - name: HTTPS_PORT
          value: "8443"
        - name: MIN_PORT
          value: "16384"
        - name: MAX_PORT
          value: "32768"
        - name: DOMAIN_OR_PUBLIC_IP
          value: "openvidu.ssafy.io"
---
apiVersion: v1
kind: Service
metadata:
  name: openvidu-service
  namespace: roundy-app
spec:
  selector:
    app: openvidu
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  type: ClusterIP
