---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openvidu-secret
  namespace: roundy-app
spec:
  encryptedData:
    OPENVIDU_SECRET: AgAQ35FK94SRCD7clnmkvoRNiDpEOwQsPoENjkAgUMOIrBCP9IEEboyBlw/0WV5+wPIpas673/WikC0z6rCkLaQiMdQygHq9E/+Qr9/SkiymcLfaEBCKR9NXa971y3T8h8xDEoBxqDFPpYs2aWr2OMulTvL4sSyi0sfUk5/I8OOFM6l5+0lm7gRdKkVNnuGPq++LbQDa/e6gxNHG48kGLoS2OIHIZMwV9Lv5OB9qCK/qA2Jc0tV0xGLQvfinFfqFLwuDj288H1LTVkMiLrFFKGdf9kqJE1p/CxtBfOdr1Klr+YkYmrqQUHF+8Ldj/FnOUXULRVdnhRL6CYbxjQ4Xd7K2GmlodYS+nLyDvKMi4zQo1BkUI1KDihVosinuR+duEpVXk7lRWTtGZmNIZ4s/16ct3jIWecAaggY4VRt5KJ+HKA1gaSoAwDwUDOVxL9tbS7g+5U4Uv4n5q+7ytxsw5PgwnpTRICPtr1LvbFhuajJwsnH8ix+/3iUIFYEYok1AniTLDcWvbIj6cBEAA7hPyVyO9Velh5cXer6kWLRjilqBvXUUlZftjpZoPWJr4AJjYJJfb4m0BAreRBIaWAdmvgm5uZy25ixq4p6+ckO545QtDMO8t0IAA8jdPs2i9XEbNWneNFgAR3AfO7t0tr8aHEJjlPdLLPBQ+jGon0ppRoDVGe21dg24+8gWONib6TaMyQ3bDgaNk04sCk5/+BmLdw==
  template:
    metadata:
      name: openvidu-secret
      namespace: roundy-app
    type: Opaque
