apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openvidu-ingress
  namespace: roundy-app
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: openvidu.ssafy.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openvidu-service
            port:
              number: 8443