pipeline {
    agent any

    environment {
        DOCKER_USER = 'smj100394'
        REPO_NAME = 'roundy_front'
        IMAGE_TAG = "${DOCKER_USER}/${REPO_NAME}:${BUILD_NUMBER}"
        DOCKERHUB_CREDENTIALS_ID = 'dockerhub'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Docker Build') {
            steps {
                script {
                    dir('Frontend') {
                        sh "sudo docker build -t ${IMAGE_TAG} ."
                    }
                }
            }
        }

        stage('Docker Push') {
            steps {
                script {
                    docker.withRegistry('', DOCKERHUB_CREDENTIALS_ID) {
                        sh "sudo docker push ${IMAGE_TAG}"
                        sh "sudo docker tag ${IMAGE_TAG} ${DOCKER_USER}/${REPO_NAME}:latest"
                        sh "sudo docker push ${DOCKER_USER}/${REPO_NAME}:latest"
                    }
                }
            }
        }

        stage('Cleanup') {
            steps {
                sh "sudo docker rmi ${IMAGE_TAG}"
                sh "sudo docker rmi ${DOCKER_USER}/${REPO_NAME}:latest"
            }
        }
    }
}