-- Database Dump / Seed Data
-- This file contains the initial seed data used for the Roudy application.
-- Since the schema is auto-generated by JPA (ddl-auto=update/create), this file primarily ensures 
-- that essential preference checks and static data are populated.

-- Preference 초기 데이터
-- 초기화: 기존 데이터 삭제 (중복 누적 방지)

SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM preferences;
ALTER TABLE preferences AUTO_INCREMENT = 1;

-- 선호관계 (RELATIONSHIP_GOAL)
INSERT INTO preferences (type, content)
SELECT * FROM (
    SELECT 'RELATIONSHIP_GOAL', '결혼 의향도 있어요' UNION ALL
    SELECT 'RELATIONSHIP_GOAL', '진지한 연애' UNION ALL
    SELECT 'RELATIONSHIP_GOAL', '일단 연애부터' UNION ALL
    SELECT 'RELATIONSHIP_GOAL', '일단 친구부터' UNION ALL
    SELECT 'RELATIONSHIP_GOAL', '아직 모르겠어요'
) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM preferences WHERE type = 'RELATIONSHIP_GOAL' LIMIT 1);

-- 연애 스타일 (DATING_STYLE)
INSERT INTO preferences (type, content)
SELECT * FROM (
    SELECT 'DATING_STYLE', '다정한 스킨십' UNION ALL
    SELECT 'DATING_STYLE', '상대한테 맞춰줘요' UNION ALL
    SELECT 'DATING_STYLE', '깜짝 선물' UNION ALL
    SELECT 'DATING_STYLE', '응원과 격려' UNION ALL
    SELECT 'DATING_STYLE', '함께 시간 보내기' UNION ALL
    SELECT 'DATING_STYLE', '꾸준한 연락' UNION ALL
    SELECT 'DATING_STYLE', '취미/관심사 공유' UNION ALL
    SELECT 'DATING_STYLE', '소소한 이벤트' UNION ALL
    SELECT 'DATING_STYLE', '표현을 잘해요' UNION ALL
    SELECT 'DATING_STYLE', '꼼꼼한 데이트 계획' UNION ALL
    SELECT 'DATING_STYLE', '한 사람만 봐요'
) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM preferences WHERE type = 'DATING_STYLE' LIMIT 1);

-- 선호 데이트 (DATE_PREFERENCE)
INSERT INTO preferences (type, content)
SELECT * FROM (
    SELECT 'DATE_PREFERENCE', '집에서 놀기' UNION ALL
    SELECT 'DATE_PREFERENCE', '근교 드라이브하기' UNION ALL
    SELECT 'DATE_PREFERENCE', '요리해먹기' UNION ALL
    SELECT 'DATE_PREFERENCE', '맛집 투어하기' UNION ALL
    SELECT 'DATE_PREFERENCE', '쇼핑하기' UNION ALL
    SELECT 'DATE_PREFERENCE', '카페 투어하기' UNION ALL
    SELECT 'DATE_PREFERENCE', '같이 술 마시기' UNION ALL
    SELECT 'DATE_PREFERENCE', '노래방 가기' UNION ALL
    SELECT 'DATE_PREFERENCE', '놀이공원 가기' UNION ALL
    SELECT 'DATE_PREFERENCE', '동네 구경하기' UNION ALL
    SELECT 'DATE_PREFERENCE', '산책하기' UNION ALL
    SELECT 'DATE_PREFERENCE', '영화 보러가기' UNION ALL
    SELECT 'DATE_PREFERENCE', '전시회 보러가기' UNION ALL
    SELECT 'DATE_PREFERENCE', '같이 운동하기' UNION ALL
    SELECT 'DATE_PREFERENCE', '같이 게임하기' UNION ALL
    SELECT 'DATE_PREFERENCE', '공연/콘서트 관람하기' UNION ALL
    SELECT 'DATE_PREFERENCE', '스포츠 관람하기' UNION ALL
    SELECT 'DATE_PREFERENCE', '여행가기'
) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM preferences WHERE type = 'DATE_PREFERENCE' LIMIT 1);

-- 성격 (PERSONALITY)
INSERT INTO preferences (type, content)
SELECT * FROM (
    SELECT 'PERSONALITY', '웃음이 많아요' UNION ALL
    SELECT 'PERSONALITY', '예의가 발라요' UNION ALL
    SELECT 'PERSONALITY', '긍정적인 마인드' UNION ALL
    SELECT 'PERSONALITY', '솔직해요' UNION ALL
    SELECT 'PERSONALITY', '다정해요' UNION ALL
    SELECT 'PERSONALITY', '배려심이 깊어요' UNION ALL
    SELECT 'PERSONALITY', '동물을 좋아해요' UNION ALL
    SELECT 'PERSONALITY', '털털해요' UNION ALL
    SELECT 'PERSONALITY', '장난기가 많아요' UNION ALL
    SELECT 'PERSONALITY', '애교가 많아요' UNION ALL
    SELECT 'PERSONALITY', '허세 없어요' UNION ALL
    SELECT 'PERSONALITY', '유머 감각이 있어요' UNION ALL
    SELECT 'PERSONALITY', '섬세해요' UNION ALL
    SELECT 'PERSONALITY', '수줍어요' UNION ALL
    SELECT 'PERSONALITY', '낙천적이에요' UNION ALL
    SELECT 'PERSONALITY', '활발해요' UNION ALL
    SELECT 'PERSONALITY', '감성적이에요' UNION ALL
    SELECT 'PERSONALITY', '친절해요' UNION ALL
    SELECT 'PERSONALITY', '엉뚱해요' UNION ALL
    SELECT 'PERSONALITY', '성실해요' UNION ALL
    SELECT 'PERSONALITY', '리드하는 편' UNION ALL
    SELECT 'PERSONALITY', '조용해요' UNION ALL
    SELECT 'PERSONALITY', '직진해요'
) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM preferences WHERE type = 'PERSONALITY' LIMIT 1);

-- 외모 (APPEARANCE)
INSERT INTO preferences (type, content)
SELECT * FROM (
    SELECT 'APPEARANCE', '강아지상' UNION ALL
    SELECT 'APPEARANCE', '고양이상' UNION ALL
    SELECT 'APPEARANCE', '눈웃음' UNION ALL
    SELECT 'APPEARANCE', '동안이에요' UNION ALL
    SELECT 'APPEARANCE', '큰 눈' UNION ALL
    SELECT 'APPEARANCE', '손이 예뻐요' UNION ALL
    SELECT 'APPEARANCE', '깨끗한 피부' UNION ALL
    SELECT 'APPEARANCE', '하얀 피부' UNION ALL
    SELECT 'APPEARANCE', '구릿빛 피부' UNION ALL
    SELECT 'APPEARANCE', '비율이 좋아요' UNION ALL
    SELECT 'APPEARANCE', '보조개' UNION ALL
    SELECT 'APPEARANCE', '다리가 예뻐요' UNION ALL
    SELECT 'APPEARANCE', '쌍커풀 없는 눈' UNION ALL
    SELECT 'APPEARANCE', '오똑한 콧날' UNION ALL
    SELECT 'APPEARANCE', '힙업' UNION ALL
    SELECT 'APPEARANCE', '짙은 눈썹' UNION ALL
    SELECT 'APPEARANCE', '실물파'
) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM preferences WHERE type = 'APPEARANCE' LIMIT 1);

-- 재능 (TALENT)
INSERT INTO preferences (type, content)
SELECT * FROM (
    SELECT 'TALENT', '이야기를 잘 들어줘요' UNION ALL
    SELECT 'TALENT', '대화를 잘 이끌어요' UNION ALL
    SELECT 'TALENT', '뭐든 잘 먹어요' UNION ALL
    SELECT 'TALENT', '혼자 잘 놀아요' UNION ALL
    SELECT 'TALENT', '요리를 잘해요' UNION ALL
    SELECT 'TALENT', '패션 센스가 좋아요' UNION ALL
    SELECT 'TALENT', '운동을 좋아해요' UNION ALL
    SELECT 'TALENT', '목소리가 좋아요' UNION ALL
    SELECT 'TALENT', '체력이 좋아요' UNION ALL
    SELECT 'TALENT', '노래를 잘해요' UNION ALL
    SELECT 'TALENT', '섹시한 두뇌' UNION ALL
    SELECT 'TALENT', '시사에 밝아요' UNION ALL
    SELECT 'TALENT', '게임을 잘해요' UNION ALL
    SELECT 'TALENT', '높은 경제력' UNION ALL
    SELECT 'TALENT', '고소득자' UNION ALL
    SELECT 'TALENT', '운전 잘해요' UNION ALL
    SELECT 'TALENT', '집안일 잘해요' UNION ALL
    SELECT 'TALENT', '적극적인 플러팅'
) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM preferences WHERE type = 'TALENT' LIMIT 1);

SET FOREIGN_KEY_CHECKS = 1;

