pipeline {
    agent{
        kubernetes{
            yaml'''
              apiVersion: v1
              kind: Pod
              spec:
                containers:
                - name: gradle
                  image: gradle:8.14.3-jdk21
                  command:
                  - cat
                  tty: true
                - name: docker
                  image: docker:29.1.3
                  command:
                  - cat
                  tty: true
                  volumeMounts:
                  - mountPath: /var/run/docker.sock
                    name: docker-sock
                volumes:
                - name: docker-sock
                  hostPath:
                    path: /var/run/docker.sock
            '''
        }
    }

    environment {
        DOCKER_USER = 'smj100394' 
        REPO_NAME = 'roundy_back'
        IMAGE_TAG = "${DOCKER_USER}/${REPO_NAME}:${BUILD_NUMBER}"
        DOCKERHUB_CREDENTIALS_ID = 'dockerhub'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build gradle') {
            steps {
                container('gradle') {
                    dir('Backend') {
                        sh "chmod +x ./gradlew"
                        sh "./gradlew clean build -x test"
                    }
                }
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                container('docker') {
                    withCredentials([usernamePassword(credentialsId: "${DOCKERHUB_CREDENTIALS_ID}", 
                                                      passwordVariable: 'DOCKER_PASSWORD', 
                                                      usernameVariable: 'DOCKER_USERNAME')]) {
                        dir('Backend') {
                            script {
                                sh "echo \$DOCKER_PASSWORD | docker login -u \$DOCKER_USERNAME --password-stdin"
                                
                                sh "docker build -t ${IMAGE_TAG} ."
                                sh "docker push ${IMAGE_TAG}"
                                
                                sh "docker tag ${IMAGE_TAG} ${DOCKER_USER}/${REPO_NAME}:latest"
                                sh "docker push ${DOCKER_USER}/${REPO_NAME}:latest"
                                
                                sh "docker logout"
                            }
                        }
                    }
                }
            }
        }

        stage('Cleanup') {
            steps {
                container('docker') {
                    sh "docker rmi ${IMAGE_TAG}"
                    sh "docker rmi ${DOCKER_USER}/${REPO_NAME}:latest"
                }
            }
        }
    }
}