---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: front-env-secret
  namespace: roundy-app
spec:
  encryptedData:
    VITE_API_URL: AgAIelcxFEMNBlBi+1uEZhhYfjcgyaQbXK/KEEB3wCGPe02btmuSGSKM/umsypN6XABb6U4xganXTXHO1HcvyrAmPYPdQ6oo2+Xv6nUxX83HgB7po9SxVVD1nmDFVOozdTaom21eLkgz8SAf+lWf1h/lMh/pnBQfv5oVd2oqVCYue6AT9I4QCOB2N0IidnOZTR/1fmTjVTM7CCtG+xW5zMoSWdCtU8DuFAp+Rwy6RsyB0vWYVD1WX4PS1Cv1GR/5S1dmEvB+NYqe4dcULQ6H9LfsIjUQDlvpiBJIBWufM1lAPnuQ+09OSEbYjS6ZwgWUbZQSwLFpRVnR9G9ZiMtwo+IWmf75liuFE1PeCnjfi64GgGab9sqIgFX6/OOFpcXlWdvRZiWXfiUTaFcWx77xAsMcsWsRkxCeDEtFzwKakakzrvT3biOe7sbA+VwgfhmwUp+q0Hwb4dnsSd+X1z1M2MkpNB4oGgvIccWQ4qVeqJ0vIPfq1hidS7mQutCbRZjKyGs1p01pPzpEnDJaG9On76xfuoY0MMxOuZXz9WO/c73JTtueYD5hzrkhY+KKrsZbWlJek3jM2Ka3XFElZOnYHRTv6YrjjCIOK5OcgpWatwO2gdRUCeQ1dkbbC1EZW+gtKvGb58oKGj5XmkGRdaKofcyaF+s378MZL4+Xmxf+HPswEKevdorNy27aT18GLERM5OeE4QMgt+bSBCBAkEohCKPU/u15g4M6CXmhxA==
    VITE_WS_URL: AgDj2yv5mJIaVNNcDtHIHUxpQAxstayOP8Yw+MW4lWWCDPzgxaeAcgLq50CvWY+KoPIUItdbQ+rMFsbCOeGOvtwz1KfWIXibQOgI7ZaaL0rwLTqmR4n/AuaLa+J1NCnkfOFG7eM98L7BfnTEkHZcLKohJe+EvCvJXe/aveV7kkTFkoX8yyAG8Go7oCKUZ4C2R0FEC/juCi6NuWyUcQ5Vn8wVzU7Wt9a7Jqqhqw8mmNs6b1QBgZB+JXU+i5uE/DkPGX6IfXZtaaG1687686SO1G9kz1gwCa9xuGZM8UymwIyChQ6Ijfyl3MWQOfmSk0ovubPOtXuMc/CgQUllceuWqKmEAy8tqvKGC5Hu6KlHB5JXsW8zr7ayIANQz4WXGklo/aCSJyoyLSDvLdAzbhFjfFVOjrWYgsFMX/owsYF/bMo0a0ezBMTdb8jqFF+ZExklLpgtWRIuMfWGCNBZzphUt4EuOJqF+V+kqBwQHeKeb+cCII7eeiIh5KgwrfUDnk8hUA9iBXNhV1W1r6SVD/1mvtndCoNG+XYNfgzNQeAKtUQJ87CCFdkWl9Rm0SGqKSR6ouZBTUkDTtRI+BKphF3Xe5A74TYEFDCLdT9Z3WoO7LV2WTqoztCyg3BYJykOqQWZ9+fCgwV4tysAcJJDwtj6fF30JRvSATqiya8ClymPM/bIXPNqs0CBnOfle0K5QhMfrkmb6VYJX6G+darZcnMb+7tSwmF/bgrPj+a4Enmqcv1TUiHBR8sOSw==
  template:
    metadata:
      name: front-env-secret
      namespace: roundy-app
    type: Opaque
