---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: front-env-secret
  namespace: roundy-app
spec:
  encryptedData:
    VITE_API_URL: AgDG5f9KAd2PXOBzf6Dt0v7SEkTdTcQVLuUmQt/G5SWLD4xcnU8gqnc2xGxHC4gX6GAEUZxsnLRBHHwAXU6WomVW/FD3ezYK+/dxaw8dg6CAWhLNMgyNgPiBRY2qCr+SSxP+LZkfMmSzFKUD7Cs7AQrfkll5Zhn+6MC5s7Dwnb2zf7iR3nm6Sxppbvgxg4e+y0CuyKCxt5vJSno63LyGvi50IBjk7Cdki1+9//CL2tjpMS1LDjdLrDYuGQMVJRkm8BWDEDoXQpEfZhfZi9lzzzZKaqYVT1QoyXPdZZPEF9i+rvrxNjclgpMn9sSelfccpM3pdEFZ9iT6KISdquAgBnM+LjwcotTWulhnBGL/UXzdUdpzms3kpoK3Po6jEXci0JpAdloTczobYNGiKMGAUytkUfoUa8Y4S9+01jKJQ9n1U75/e+9DCZh97BZtk0Ow6+5mCHqDTLiH6cOuwmePqiBOHxsYUq1bRDv3kB3C+GsLgxQ/Nye0yvbG2Fsk6CmcFNkCchKBHgv5jq9k6b4Q2NxF0/JVFBXyj8PFqTqhrVWlxGwRV3QlUhVtUvNy6TIMH2SJ4zR0hNywCWRD0nr2Jobz0z0qJQGp6bN2ni0LiSDt9+aIyXt2vl7mIdkaCDmC9lo1fnW+8DNGxeamXLAD5X3aulrQaYKfMg2Z2MikDK2Iir15bya6jOt40PfdBFvWLlhDhpDXNJCYhe5unVKRoezKAHQj64ggJi62Mg==
    VITE_WS_URL: AgAxlgLsmv8WywrxGpNcpahLTM+YT5WhREC09SCRcTxy+5IQh0Yx1S/k2zOdFqWLeibwJtWLPk4W6xKxszoUXzr8hrLN47go9bk5HM4NOG8m2hISyOgpcGRJazep9vf7/QXyUyNhWeRJd8UyO9ymPQ4UcRRQNERm6fzwNFEdB00jVbMgPS3W5Tm28kA8jxscivOsaqOFHF+V6FALVqM01mWpKk+jVP5Z2hhwnfGLU+Ed6KkR7/G9inr/YWROC1F78gjYysbGvO6SeV6X3fZC8b/3T+PZfHSkmhlf5ckMHCDlFjLpCdTf/2iGPcl9lKmOySst3g2BaEQwclu9qppfl/vr2MTPjKb0/huHJI/uHKjxtGh4VwEXgrdl1eM8Z1OPoRSkXRE5jNsaPdGJ7Rmar/XPSRIuzUGiWvP1HUuMDMlPT7I/J4ALv/7jns93vsM10a7FRRc+Bk0gFqH5/PSgrzcHP4trr4U/Wb37VkuHaCKx2+/nyblok8bRZCI+Tl4LcGaO4DaNpum3OHgDE3e/ExBP2WkHXIOxxsz8iKfbJECqoeYxZ0ZLj+py4jQcbcBENYlPbOfJUYBg3g3RDqq6KSDep1BkoilpvGOdAwFOl17H8rnPRz4L1ypiqW+GfDs0kSlhHnZWVYq1tzJvxJ8rwieiZKk22BbyK22+7uLwZbfHNtffaNUX9wHCFfpiaGXr1MvpT3wo+NRFPdVK1fK5CMzA27rxjWLF6faTjbf6YFnN34WFj0f6zw==
  template:
    metadata:
      name: front-env-secret
      namespace: roundy-app
    type: Opaque
