---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: front-env-secret
  namespace: roundy-app
spec:
  encryptedData:
    VITE_WS_URL: AgCyxCM5iMLx4yP4eVnv49N4LQEkYEFlEH6L2sygatf+RFECgep/6hE99TeqHuaeiw73500VwOgt86czQELVhcm4PQBGxrAZlACgu6zYWNZQ7GJ4qDYflZUTTKS7qkdeKE+d+jdHmljPnt3Toz13I91cJzQLOIcfqVpbBCy//medqWMB/G7W7AY25WyAwZlCWqQoTAH+Yc8GKK1v+NDeYwAZ6KH48htcJ6gLO5CC2GF5MndRMoaLe3UbItfN1WALe499jqYwA0ZLwIgUXAju1uJYXAnNXLVhopNZL0KQNPuWsLc671Wjvu7grwy5IZAKTpCp8BPaIyS21q5cnLxMPHR310TFb9MP+vNzkUDRFdDxfgGv9U4Q2/qERFxHKwYVU4c/pEf6Nwfwb6e2lp9dL1h8YSxRceFdzlmlPTYFA6iBBBHFXhH5yv6On2eknmEVGY5+UobdnDcUO280Ebhd1mZbaJwYIAyiNWl6Z8mQP7SdVdtGgKrBI43oMkUwZm/uhPN5hvccj/dx3PlaQH/vtC3X31608xflU+FRtEGqZ0GthP7GQ2i2kY3Q0Oi2eWaCdWNbyFapePQNZoC8S8oSBdndrVL5ofwAH7+kaCm4ta7zlrmFaocydYOWW8YIDDUe+cQ2GcWwfQi4hpVnQQwtBRCAVvPX5xRqQsE6VqwvPLALIlRN2xdSf7eMp5EzrOUT/hXmT/ERhU+eF5m7wyi1shlq0TL0z1zLMSPTp6qUWpa3g/U9QGJfPA==
  template:
    metadata:
      name: front-env-secret
      namespace: roundy-app
    type: Opaque
