apiVersion: v1
kind: Service
metadata:
  name: roundy-frontend-svc
  namespace: roundy-app
spec:
  selector:
    app: roundy-frontend 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP