
export const TEST_TOKENS = [
  // M1 (userId: 2)
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMCIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzcwNDUxMjUwLCJleHAiOjE3NzA2MjQwNTB9.I1RTxsClu7fv0HlBwhM0F-kJPM8fAHcMFv3EVvNz2fc',

  // M2 (userId: 3)
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzcwNDUxMjUwLCJleHAiOjE3NzA2MjQwNTB9.u-fok2xGE5COB-GvH1C_8KTu7uQyZdHpi8BitjLcJyw',

  // M3 (userId: 4)
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzcwNDUxMjUwLCJleHAiOjE3NzA2MjQwNTB9.Cmv-txcr2fpdDnezKSnO0-IHiJ8N3s4Q61LglHO-mvQ',

  // F1 (userId: 5)
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNCIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzcwNDUxMjUwLCJleHAiOjE3NzA2MjQwNTB9.5367ANJ_YKWRlTKAyoWA4z-asDZLRIupTkcBBU1MQkk',

  // F2 (userId: 6)
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzcwNDUxMjUwLCJleHAiOjE3NzA2MjQwNTB9.0o89BZ_tkm27ENPp_h3jg34bPcGXlAQYdRCOT2RPZhg',

  // F3 (userId: 7)
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzcwNDUxMjUwLCJleHAiOjE3NzA2MjQwNTB9.kMOzAB21cUCFlRxefIZuQBYHeCQeWvR9KBoyRM0VMa8',
];
