apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundy-backend
  namespace: roundy-app
  labels:
    app: roundy-backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: roundy-backend
  template:
    metadata:
      labels:
        app: roundy-backend
    spec:
      containers:
      - name: backend-container
        image: smj100394/roundy_back:137
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: OPENVIDU_URL
          value: "http://openvidu-service:443" # Internal Service URL (HTTP)
        envFrom:
        - secretRef:
            name: roundy-backend-secrets
