apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundy-backend
  namespace: roundy-app
  labels:
    app: roundy-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roundy-backend
  template:
    metadata:
      labels:
        app: roundy-backend
    spec:
      containers:
      - name: backend-container
<<<<<<< HEAD
        image: smj100394/roundy_back:latest
=======
        image: smj100394/roundy_back:12
>>>>>>> cf2695af9e5ab747bfd1aae93df4df63913b0abf
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
