
spring.application.name=roundy

# .env 파일 경로
spring.config.import=optional:classpath:.env[.properties]

# MYSQL 설정
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA, Hibernate 설정
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:none}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# SQL 초기화 (data.sql 자동 실행)
# TODO : 인프라 분과 논의 필요
# JPA가 먼저 테이블 생성하고, 그 다음 data.sql 실행
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Redis 설정
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

app.frontend-url=${APP_FRONTEND_URL}

# 카카오
kakao.client-id=${KAKAO_CLIENT_ID}
kakao.redirect-uri=http://localhost:8080/api/auth/kakao/callback
kakao.secret-key=${KAKAO_SECRET_KEY}
kakao.admin-key=${KAKAO_ADMIN_KEY}

#jwt
jwt.secret=${JWT_SECRET:test-secret-key-for-webrtc-development-minimum-32-bytes}
# TEST를 위해 2일로 설정 추후에 24시간으로 바꿔야함
jwt.expiration-time=172800000

# 우리 프로젝트 패키지의 로그 레벨을 INFO로 설정
logging.level.com.ssafya701.roundy=INFO

# file uploader
file.upload-dir=uploads/

# OpenVidu 설정
openvidu.url=${OPENVIDU_URL:https://openvidu.example.com}
openvidu.secret=${OPENVIDU_SECRET}


# WebRTC WebSocket 설정
webrtc.ws.path=/ws/webrtc
webrtc.round.duration-seconds=${WEBRTC_ROUND_DURATION:300}
webrtc.round.interval-seconds=${WEBRTC_ROUND_INTERVAL:10}